---
language: node_js
node_js:
  - "0.12"

sudo: false

cache:
  directories:
    - node_modules

env:
  - EMBER_TRY_SCENARIO=default
  - EMBER_TRY_SCENARIO=ember-release
  - EMBER_TRY_SCENARIO=ember-beta
  - EMBER_TRY_SCENARIO=ember-canary
  - EMBER_TRY_SCENARIO=ember-1.13.13
  - EMBER_TRY_SCENARIO=ember-2.0.3
  - EMBER_TRY_SCENARIO=ember-2.1.2
  - EMBER_TRY_SCENARIO=ember-2.2.2
  - EMBER_TRY_SCENARIO=ember-2.3.1

matrix:
  fast_finish: true
  allow_failures:
    - env: EMBER_TRY_SCENARIO=ember-beta
    - env: EMBER_TRY_SCENARIO=ember-canary

before_install:
  - export PATH=/usr/local/phantomjs-2.0.0/bin:$PATH
  - "npm config set spin false"
  - "npm install -g npm@^2"

install:
  - npm install -g bower
  - npm install
  - bower install

script:
  - ember try $EMBER_TRY_SCENARIO test

addons:
  code_climate:
    repo_token: 8eea650d4493e34429bf149a5b9d68f78963b56410568902bf9d52eed54c8cc5

after_script:
  - codeclimate < lcov.dat
